CREATE TABLE "CRE_Data" (
    "id" INT   NOT NULL,
    "MSAYear" VARCHAR   NOT NULL,
    "SpecialKey" VARCHAR   NOT NULL,
    "MSA_Name" VARCHAR   NOT NULL,
    "Property_Class_Name" VARCHAR   NOT NULL,
    "Period" VARCHAR   NOT NULL,
    "Qtr" INT   NOT NULL,
    "Yr" INT   NOT NULL,
    "Slice" VARCHAR   NOT NULL,
    "As_of" VARCHAR   NOT NULL,
    "Geography_Name" VARCHAR   NOT NULL,
    "Property_Type" VARCHAR   NOT NULL,
    "Geography_Code" VARCHAR   NOT NULL,
    "Forecast_Scenario" VARCHAR   NOT NULL,
    "CBSA_Code" INT   NOT NULL,
    "Geography_Type" VARCHAR   NOT NULL,
    "Stock" INT    NULL,
    "Vacancy" DECIMAL    NULL,
    "Occupancy" DECIMAL   NULL,
    "Asking_Rent" DECIMAL    NULL,
    "Asking_Rent_Index" DECIMAL    NULL,
    "Rent_Growth" DECIMAL    NULL,
    "Rent_Growth_12_Month" DECIMAL    NULL,
    "Demand" INT    NULL,
    "Net_Absorption" INT    NULL,
    "Net_Absorption_12_Months" INT    NULL,
    "Net_Completions_12_Months" INT    NULL,
    "Cap_Rate" DECIMAL    NULL,
    "Total_Return" DECIMAL    NULL,
    "Income_Return" DECIMAL    NULL,
    "Appreciation_Return" DECIMAL    NULL,
    "NOI_Index" DECIMAL    NULL,
    "Capital_Value_Index" DECIMAL    NULL,
    "Price_Index" DECIMAL    NULL,
    "Price_Growth" DECIMAL    NULL,
    "Market_Capitalization" DECIMAL    NULL,
    "Office_Employment" INT    NULL,
    "Population" INT    NULL,
    "Median_Household_Income" INT    NULL,
    "Total_Employment" INT    NULL,
    "Households" INT    NULL,
    "Industrial_Employment" INT    NULL,
    "Transaction_Cap_Rate" DECIMAL    NULL,
    "Number_Transaction_Cap_Rate" INT    NULL,
    "Transaction_PricePerArea" DECIMAL    NULL,
    "Total_Sales_Volume" INT    NULL,
    "Number_Sales_Volume" INT    NULL,
    "Sold_Building_SF" INT    NULL,
        CONSTRAINT "pk_CRE_Data" PRIMARY KEY (
        "SpecialKey"
     )
);

CREATE TABLE "Labor_Data" (
    "id" INT   NOT NULL,
    "SpecialKey" VARCHAR   NOT NULL,
    "MSAYear" VARCHAR   NOT NULL,
    "MSA_Name" VARCHAR   NOT NULL,
    "Property_Class_Name" VARCHAR   NOT NULL,
    "Period" VARCHAR   NOT NULL,
    "Qtr" INT   NOT NULL,
    "Yr" INT   NOT NULL,
    "Slice" VARCHAR   NOT NULL,
    "As_of" VARCHAR   NOT NULL,
    "Geography_Name" VARCHAR   NOT NULL,
    "Property_Type" VARCHAR   NOT NULL,
    "Geography_Code" VARCHAR   NOT NULL,
    "Forecast_Scenario" VARCHAR   NOT NULL,
    "CBSA_Code" INT    NULL,
    "Geography_Type" VARCHAR    NULL,
    "Jobs_id" VARCHAR   NOT NULL,
    "Resident_Workers_id" VARCHAR   NOT NULL,
    "Location_Quotient_id" VARCHAR   NOT NULL,
    "Jobs" DECIMAL    NULL,
    "Resident_Workers" DECIMAL    NULL,
    "Location_Quotient" DECIMAL    NULL,
    "Age_45-54_Percent_of_Region" VARCHAR    NULL,
    "Age_14-18_Percent_of_Region" VARCHAR    NULL,
    "Age_19-21_Percent_of_Region" VARCHAR    NULL,
    "Age_22-24_Percent_of_Region" VARCHAR    NULL,
    "Age_25-34_Percent_of_Region" VARCHAR    NULL,
    "Age_35-44_Percent_of_Region" VARCHAR    NULL,
    "Age_55-64_Percent_of_Region" VARCHAR    NULL,
    "Age_65_Plus_Percent_of_Region" VARCHAR    NULL,
    CONSTRAINT "pk_Labor_Data" PRIMARY KEY (
        "SpecialKey"
     )
);

ALTER TABLE "CRE_Data" ADD CONSTRAINT "fk_CRE_Data_SpecialKey" FOREIGN KEY("SpecialKey")
REFERENCES "Labor_Data" ("SpecialKey");

